import { useEffect, useState } from 'react'
import { FaPen, FaMedium } from 'react-icons/fa'

interface BlogPost {
  title: string
  excerpt: string
  date: string
  readTime: string
  url: string
  tags: string[]
  image?: string
}

function Blog() {
  const [blogPosts, setBlogPosts] = useState<BlogPost[]>([
    {
      title: 'Building, Dockerizing, and Deploying a CRUD API in Go on Kubernetes',
      excerpt: 'A comprehensive guide on building a CRUD API in Go, containerizing it with Docker, and deploying it to Kubernetes.',
      date: '2024',
      readTime: '12 min read',
      url: 'https://levelup.gitconnected.com/building-dockerizing-and-deploying-a-crud-api-in-go-on-kubernetes-9c25b01ad2e8',
      tags: ['Go', 'Kubernetes', 'Docker', 'DevOps'],
    },
    {
      title: 'Notion Automation with Apple Shortcuts',
      excerpt: 'Learn how to automate your Notion workflows using Apple Shortcuts for improved productivity.',
      date: '2024',
      readTime: '6 min read',
      url: 'https://kalharatennakoon.medium.com/notion-automation-with-apple-shortcuts-d3ccab993cc7',
      tags: ['Productivity', 'Automation', 'Notion'],
    },
    {
      title: 'Software Testing Processes for Beginners',
      excerpt: 'A beginner-friendly guide to understanding software testing processes and methodologies.',
      date: '2024',
      readTime: '8 min read',
      url: 'https://kalharatennakoon.medium.com/software-testing-processes-for-beginners-6ac5394c1d3d',
      tags: ['Testing', 'QA', 'Software Engineering'],
    },
    {
      title: 'How to Reduce Your Screen Time',
      excerpt: 'Practical tips and strategies to reduce screen time and maintain a healthier digital lifestyle.',
      date: '2024',
      readTime: '5 min read',
      url: 'https://kalharatennakoon.medium.com/how-to-reduce-screen-time-9ee6e4ed9037',
      tags: ['Productivity', 'Health', 'Lifestyle'],
    },
    {
      title: 'iOS 26 Preview: A Closer Look at the New Phone and Messages Apps',
      excerpt: "Exploring the new features and improvements in iOS 26's Phone and Messages applications.",
      date: '2025',
      readTime: '7 min read',
      url: 'https://kalharatennakoon.medium.com/ios-26-preview-a-closer-look-at-the-new-phone-and-messages-apps-e72c20ca4c84',
      tags: ['iOS', 'Apple', 'Mobile'],
    }
  ])

  useEffect(() => {
    // Fetch latest blog posts from the JSON file generated by GitHub Actions
    fetch('/blog-posts.json')
      .then(response => response.json())
      .then(data => {
        if (data && data.length > 0) {
          setBlogPosts(data)
        }
      })
      .catch(error => console.log('Using default blog posts:', error))
  }, [])

  return (
    <section id="blog" className="py-20 bg-[var(--bg-primary)] dark:bg-[var(--bg-secondary)]">
      <div className="max-w-6xl mx-auto px-8">
        <h2 className="text-5xl mb-4 text-center text-[var(--text-primary)] font-bold bg-gradient-to-r from-[var(--color-primary)] to-[var(--color-primary)] bg-clip-text text-transparent">
          Blog Posts / Writing
        </h2>

        <div className="flex items-center justify-center gap-4 max-w-3xl mx-auto mb-12 px-8 py-4 bg-gradient-to-br from-[rgba(30,58,138,0.08)] to-[rgba(23,37,84,0.08)] rounded-full border-2 border-[rgba(30,58,138,0.2)] dark:from-[rgba(30,58,138,0.12)] dark:to-[rgba(23,37,84,0.12)] dark:border-[rgba(30,58,138,0.3)]">
          <FaPen className="text-xl flex-shrink-0 text-[var(--color-primary)]" />
          <p className="m-0 text-base text-[var(--text-secondary)] font-medium text-center">
            DevOps • Cloud-Native • Engineering Insights
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          {blogPosts.map((post) => (
            <article
              key={post.title}
              className="group bg-[var(--card-bg)] rounded-2xl shadow-[0_4px_15px_var(--shadow)] transition-all duration-300 flex flex-col hover:-translate-y-2 hover:shadow-[0_12px_35px_rgba(30,58,138,0.2)] border border-[var(--border-color)] overflow-hidden"
            >
              {/* Post image */}
              <a href={post.url} target="_blank" rel="noopener noreferrer" className="block h-48 overflow-hidden bg-[rgba(30,58,138,0.06)] flex-shrink-0">
                {post.image ? (
                  <img
                    src={post.image.startsWith('//') ? `https:${post.image}` : post.image}
                    alt={post.title}
                    className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center bg-gradient-to-br from-[rgba(30,58,138,0.1)] to-[rgba(23,37,84,0.15)]">
                    <FaMedium className="text-5xl text-[rgba(30,58,138,0.3)]" />
                  </div>
                )}
              </a>

              {/* Card content */}
              <div className="p-6 flex flex-col flex-grow">
                <div className="flex gap-2 text-xs text-[var(--text-secondary)] mb-3">
                  <span>{post.date}</span>
                  <span>·</span>
                  <span>{post.readTime}</span>
                </div>
                <h3 className="text-lg font-semibold leading-snug mb-3 text-[var(--text-primary)]">
                  <a
                    href={post.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="hover:text-[var(--color-primary)] transition-colors"
                  >
                    {post.title}
                  </a>
                </h3>
                <p className="text-sm leading-relaxed text-[var(--text-secondary)] mb-4 flex-grow">
                  {post.excerpt}
                </p>
                <div className="flex flex-wrap gap-2 mb-4">
                  {post.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-3 py-1 bg-[rgba(30,58,138,0.08)] rounded-full text-xs text-[var(--color-primary)] font-medium border border-[rgba(30,58,138,0.15)]"
                    >
                      {tag}
                    </span>
                  ))}
                </div>
                <a
                  href={post.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--color-primary)] hover:gap-3 transition-all"
                >
                  <FaMedium /> Read on Medium
                </a>
              </div>
            </article>
          ))}
        </div>

        <div className="text-center">
          <a
            href="https://kalharatennakoon.medium.com"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-[var(--color-primary)] to-[var(--color-primary)] text-white rounded-xl font-semibold transition-all duration-300 hover:shadow-[0_8px_25px_rgba(30,58,138,0.4)] hover:-translate-y-1 hover:scale-105"
          >
            <FaMedium /> View All Posts on Medium
          </a>
        </div>
      </div>
    </section>
  )
}

export default Blog
