import { useEffect, useState } from 'react'
import { FaPen, FaMedium } from 'react-icons/fa'

interface BlogPost {
  title: string
  excerpt: string
  date: string
  readTime: string
  url: string
  tags: string[]
}

function Blog() {
  const [blogPosts, setBlogPosts] = useState<BlogPost[]>([
    {
      title: 'Building, Dockerizing, and Deploying a CRUD API in Go on Kubernetes',
      excerpt: 'A comprehensive guide on building a CRUD API in Go, containerizing it with Docker, and deploying it to Kubernetes.',
      date: '2024',
      readTime: '12 min read',
      url: 'https://levelup.gitconnected.com/building-dockerizing-and-deploying-a-crud-api-in-go-on-kubernetes-9c25b01ad2e8',
      tags: ['Go', 'Kubernetes', 'Docker', 'DevOps']
    },
    {
      title: 'Notion Automation with Apple Shortcuts',
      excerpt: 'Learn how to automate your Notion workflows using Apple Shortcuts for improved productivity.',
      date: '2024',
      readTime: '6 min read',
      url: 'https://kalharatennakoon.medium.com/notion-automation-with-apple-shortcuts-d3ccab993cc7',
      tags: ['Productivity', 'Automation', 'Notion']
    },
    {
      title: 'Software Testing Processes for Beginners',
      excerpt: 'A beginner-friendly guide to understanding software testing processes and methodologies.',
      date: '2024',
      readTime: '8 min read',
      url: 'https://kalharatennakoon.medium.com/software-testing-processes-for-beginners-6ac5394c1d3d',
      tags: ['Testing', 'QA', 'Software Engineering']
    },
    {
      title: 'How to Reduce Your Screen Time',
      excerpt: 'Practical tips and strategies to reduce screen time and maintain a healthier digital lifestyle.',
      date: '2024',
      readTime: '5 min read',
      url: 'https://kalharatennakoon.medium.com/how-to-reduce-screen-time-9ee6e4ed9037',
      tags: ['Productivity', 'Health', 'Lifestyle']
    },
    {
      title: 'iOS 26 Preview: A Closer Look at the New Phone and Messages Apps',
      excerpt: 'Exploring the new features and improvements in iOS 26\'s Phone and Messages applications.',
      date: '2025',
      readTime: '7 min read',
      url: 'https://kalharatennakoon.medium.com/ios-26-preview-a-closer-look-at-the-new-phone-and-messages-apps-e72c20ca4c84',
      tags: ['iOS', 'Apple', 'Mobile']
    }
  ])

  useEffect(() => {
    // Fetch latest blog posts from the JSON file generated by GitHub Actions
    fetch('/blog-posts.json')
      .then(response => response.json())
      .then(data => {
        if (data && data.length > 0) {
          setBlogPosts(data)
        }
      })
      .catch(error => console.log('Using default blog posts:', error))
  }, [])

  return (
    <section id="blog" className="py-20 bg-[var(--bg-primary)] dark:bg-[var(--bg-secondary)]">
      <div className="max-w-6xl mx-auto px-8">
        <h2 className="text-5xl mb-4 text-center text-[var(--text-primary)] font-bold bg-gradient-to-r from-[#667eea] to-[#764ba2] bg-clip-text text-transparent">
          Blog Posts / Writing
        </h2>

        <div className="flex items-center justify-center gap-4 max-w-3xl mx-auto mb-12 px-8 py-4 bg-gradient-to-br from-[rgba(102,126,234,0.08)] to-[rgba(118,75,162,0.08)] rounded-full border-2 border-[rgba(102,126,234,0.2)] dark:from-[rgba(102,126,234,0.12)] dark:to-[rgba(118,75,162,0.12)] dark:border-[rgba(102,126,234,0.3)]">
          <FaPen className="text-xl flex-shrink-0 text-[#667eea]" />
          <p className="m-0 text-base text-[var(--text-secondary)] font-medium text-center">
            DevOps • Cloud-Native • Engineering Insights
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
          {blogPosts.map((post) => (
            <article
              key={post.title}
              className="group bg-[var(--card-bg)] p-8 rounded-2xl shadow-[0_4px_15px_var(--shadow)] transition-all duration-300 flex flex-col hover:-translate-y-3 hover:shadow-[0_12px_35px_rgba(102,126,234,0.2)] border border-[var(--border-color)] hover:border-[rgba(102,126,234,0.4)] backdrop-blur-sm relative overflow-hidden"
            >
              <div className="absolute inset-0 bg-gradient-to-br from-[rgba(102,126,234,0.03)] to-[rgba(118,75,162,0.03)] opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
              <div className="mb-4 relative z-10">
                <h3 className="text-xl mb-2 leading-tight">
                  <a
                    href={post.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[var(--text-primary)] font-semibold transition-all hover:bg-gradient-to-r hover:from-[#667eea] hover:to-[#764ba2] hover:bg-clip-text hover:text-transparent"
                  >
                    {post.title}
                  </a>
                </h3>
                <div className="flex gap-2 text-sm text-[var(--text-secondary)] relative z-10">
                  <span>{post.date}</span>
                  <span>·</span>
                  <span>{post.readTime}</span>
                </div>
              </div>
              <p className="leading-relaxed text-[var(--text-secondary)] mb-4 flex-grow relative z-10">
                {post.excerpt}
              </p>
              <div className="flex flex-wrap gap-2 mb-4 relative z-10">
                {post.tags.map((tag) => (
                  <span
                    key={tag}
                    className="px-3 py-1 bg-gradient-to-r from-[rgba(102,126,234,0.1)] to-[rgba(118,75,162,0.1)] rounded-full text-xs text-[#667eea] font-semibold border border-[rgba(102,126,234,0.2)] hover:border-[rgba(102,126,234,0.4)] transition-colors"
                  >
                    {tag}
                  </span>
                ))}
              </div>
              <a
                href={post.url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-[#667eea] font-semibold text-sm transition-all hover:text-[#764ba2] inline-flex items-center gap-2 group-hover:gap-3 relative z-10"
              >
                <FaMedium /> Read on Medium
              </a>
            </article>
          ))}
        </div>

        <div className="text-center">
          <a
            href="https://kalharatennakoon.medium.com"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-8 py-4 bg-gradient-to-r from-[#667eea] to-[#764ba2] text-white rounded-xl font-semibold transition-all duration-300 hover:shadow-[0_8px_25px_rgba(102,126,234,0.4)] hover:-translate-y-1 hover:scale-105"
          >
            <FaMedium /> View All Posts on Medium
          </a>
        </div>
      </div>
    </section>
  )
}

export default Blog
